version: '3'

services:
  blockcredit:
    expose: 
      - 3000-9000
    ports: 
      - 3000:3000
      - 8080:8080
    image: blockcredit:latest
    build:
      context: ./
    command: ["3000", "-h"]
    networks: 
      - main
  blockcredit2:
    expose:
      - 3000-9000
    ports:
      - 3005:3005
      - 8081:8080
    image: blockcredit:latest
    command: ["3005", "-h", "blockcredit:3000"]
    networks: 
      - main
  blockcredit3:
    ports:
    - 3010:3010
    image: blockcredit:latest
    command: ["3010", "blockcredit:3000"]
    networks: 
      - main
  blockcredit4:
    ports:
      - 3020:3020
    image: blockcredit:latest
    command: ["3020", "blockcredit2:3005"]
    networks: 
      - main

networks: 
  main:
