// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitializeContainer() (*Container, error) {
	db := ProvideLevelDb()
	mainDb := ProvideDb(db)
	container := ProvideContainer(mainDb)
	return container, nil
}
